### ISSUE TITLE
Add support for krakjoe/parallel

### ISSUE THREAD

**Issue by theofidry** [phpbrew/phpbrew#1017]
Right now there is no known variants for [krakjoe/parallel](https://github.com/krakjoe/parallel), is there a way to add it?

**Comment by herb123456** [comment]
try this?
[installing-extension-from-github](https://github.com/phpbrew/phpbrew/wiki/Extension-Installer#installing-extension-from-github)

**Comment by morozov** [comment]
Not sure if a variant can be added for a PECL extension. `phpbrew ext install parallel` should work.

**Comment by theofidry** [comment]
Actually works fine that way, there is only two issues:

- It currently needs the shared flag
- It needs the ZTS version (might be detected when compiling the extension I guess)

**Comment by morozov** [comment]
> It currently needs the shared flag.

That's why I'd recommend installing it via `phpbrew ext install`. Otherwise, you'd still have to enable it after installation.

> It needs the ZTS version (might be detected when compiling the extension I guess)

Yeah. If it fails, this would be the last message in the build log which is easy to spot.

I believe unless it requires some tricky discovery and/or complex configuration (like `gd` for instance), I'd rather have this extension to be documented in Wiki than supported as a variant. There's no point in adding every single PECL extension to variants. Later, they will require extra maintenance and create extra friction (see #950).

**Comment by theofidry** [comment]
>>It currently needs the shared flag.
>That's why I'd recommend installing it via phpbrew ext install

I don't understand that part, how do you tell to install it with the shared flag via `ext isntall`?

>Later, they will require extra maintenance and create extra friction (see #950).

It might be worth trying to tackle this issue properly, as it's a problem that can affect virtually _any_ extension...

**Comment by morozov** [comment]
> I don't understand that part, how do you tell to install it with the shared flag via `ext isntall`?

If it's the same `shared` flag as in `gd`,
https://github.com/phpbrew/phpbrew/blob/34ebc30e6962b523fba627b66109fe5b552dd2f1/src/PhpBrew/VariantBuilder.php#L426

it doesn't need to be passed to `ext install`. It only needs to be used with compiling an extension together with the binary in order to tell the compiler to produce a separate binary (a shared extension). `ext install` always produces a shared binary by definition.

I don't see any mention of this flag in the [parallel's documentation](https://github.com/krakjoe/parallel/blob/develop/INSTALL.md).

As for other arbitrary flags, they can be passed to the installer like this: `phpbrew ext install parallel -- --enable-parallel-coverage --enable-parallel-dev`.

> It might be worth trying to tackle this issue properly, as it's a problem that can affect virtually _any_ extension...

That's why I don't think that we should be adding all extensions to variants. Only the ones which are hard to install manually.

**Comment by theofidry** [comment]
Ah I see. Is it mentioned anywhere in the doc how can I have missed that?

>That's why I don't think that we should be adding all extensions to variants. Only the ones which are hard to install manually.

No I rather mean that variants should depend of the PHP version. Otherwise the variant may be valid for PHP 5.5 but not anymore for PHP 7.4...

**Comment by morozov** [comment]
> Is it mentioned anywhere in the doc how can I have missed that?

Yes. See [install extensions with customized options](https://github.com/phpbrew/phpbrew/wiki/Extension-Installer#install-extensions-with-customized-options).
