### ISSUE TITLE
Allow to enable shared mode for an extension

### ISSUE THREAD

**Issue by theofidry** [phpbrew/phpbrew#1018]
Example:

```
$ phpbrew install 7.3 +default +intl=shared,/usr/local/opt/icu4c/ +zts
```

This syntax seems to be [indicated for `gd`](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#can-not-configure-with-gd) but doesn't seem to work with other variants like `intl` here.

For clarity, when `shared` is present here it should add the flag `--enable-intl=shared`, I am not 100% sure it's the same for other extensions

**Comment by morozov** [comment]
It's already possible to compile PHP without the extension and then compile the extension. That won't work for MySQL extensions but that's a corner case. Why do we need to have another way of doing that?

**Comment by peter279k** [comment]
According to the [official PHP website](https://www.php.net/manual/en/intl.installation.php), the intl extension compiling is only available for using the `--enable-intl` option.

Unlike [GD](https://www.php.net/manual/en/image.installation.php), and it can use the `--with-gd=[DIR]` option.

**Comment by theofidry** [comment]
@peter279k it appears it's at the very least not complaining about it, do you think it would be worth adding a validation of the option's values?

**Comment by peter279k** [comment]
I don't think it's the great idea to validate the variants because the PHPBrew is the building tool.

When using the `+intl` or `+intl=shared`, the PHPBrew will fix it to the `--enable-intl` automatically during `configure` task building.

I think it should check the official PHP website and know how to use the correct `configure` options.

I also look at your [issue](https://github.com/phpbrew/phpbrew/issues/1243) and I think it's related to this one :).
