### ISSUE TITLE
PDO drivers installation

### ISSUE THREAD

**Issue by deep12650** [phpbrew/phpbrew#1143]
### Output

```
checking for PDO includes... checking for PDO includes...
configure: error: Cannot find php_pdo_driver.h.
Error: Configure failed: configure: error: Cannot find php_pdo_driver.h.
```
### Command
```
    Deeps-MBP:~ deepsachan$ phpbrew --debug install --stdout 7.2 +default +gd +soap +pear +pdo +sqlite +mysql +zlib=`brew --prefix zlib` +editline -- --enable-maintainer-zts --with-gd=shared
```
OS:
    OS X 10.15, Catalina

Running PHP: 
php 7.2.26
Installing PHP:
php 7.2.26

**Comment by morozov** [comment]
I can't reproduce this. Just tried on a fresh Mojave VM:
```
$ phpbrew --debug install --stdout 7.2 +default +gd +soap +pear +pdo +sqlite +mysql +zlib= +editline -- --enable-maintainer-zts --with-gd=shared
...
checking for PDO includes... checking for PDO includes... /Users/morozov/.phpbrew/build/php-7.2.26/ext
checking Oracle OCI support for PDO... no
```
This is where the missing file is expected to be located:
```
$ ls -l ~/.phpbrew/build/php-7.2.26/ext/pdo/php_pdo_driver.h
-rw-r--r--  1 morozov  staff  24815 Dec 17 04:30 /Users/morozov/.phpbrew/build/php-7.2.26/ext/pdo/php_pdo_driver.h
```
Could you check if it exists in your case? If not, then please try removing and installing PHP.

**Comment by deep12650** [comment]
> I can't reproduce this. Just tried on a fresh Mojave VM:
> 
> ```
> $ phpbrew --debug install --stdout 7.2 +default +gd +soap +pear +pdo +sqlite +mysql +zlib= +editline -- --enable-maintainer-zts --with-gd=shared
> ...
> checking for PDO includes... checking for PDO includes... /Users/morozov/.phpbrew/build/php-7.2.26/ext
> checking Oracle OCI support for PDO... no
> ```
> 
> This is where the missing file is expected to be located:
> 
> ```
> $ ls -l ~/.phpbrew/build/php-7.2.26/ext/pdo/php_pdo_driver.h
> -rw-r--r--  1 morozov  staff  24815 Dec 17 04:30 /Users/morozov/.phpbrew/build/php-7.2.26/ext/pdo/php_pdo_driver.h
> ```
> 
> Could you check if it exists in your case? If not, then please try removing and installing PHP.

File doesn't exist for me. Let me reinstall PHP.

**Comment by deep12650** [comment]
This issue has been resolved. My PHP build didn't have the php_pdo_driver.h but I will still recommend patching existing build with the new one if build successful and must be generated from the source not from the existing build if new options include.

**Comment by morozov** [comment]
@deep12650 by patching, do you mean unpacking the distribution package on top of already unpacked sources replacing the existing files?

It makes sense in this case. Another benefit of doing that is that we'll be able to apply the bundled patches cleanly again instead of seeing the messages from `patch` like "the file is already patched".

There are more consideration to be taken into account before making a code change?

1. Why we're keeping the existing sources at all? Why doesn't `phpbrew install` remove the entire source directory and create it from scratch?
2. What about installing extensions? Installing an extension will need some source files which may be missing for an unknown reason like here. How do we handle this?

In any event, a pull request is welcome.
