### ISSUE TITLE
/etc/init.d/phpbrew-fpm is not writable.

### ISSUE THREAD

**Issue by akoSalman** [phpbrew/phpbrew#1156]
### Output

```
*WARNING* php-fpm --pid option requires php >= 5.6. You need to update your php-fpm.conf for the pid file location.
/etc/init.d/phpbrew-fpm is not writable.

```

### Command
phpbrew fpm setup --initd

### Platform

OS:
   Debian 8

Running PHP: 7.3.10

**Comment by peter279k** [comment]
I don't have the `Debian 8`, but I use the `Debian 10` to try to reproduce the issue. Here are my steps to build/compile `PHP 7.3` in `Debian 10`:

- Prepare fresh and clean Debian 10.
- Install some required packages with `apt install` command.
- Install the PHPBrew `1.27.0` version.
- Running the `phpbrew install 7.3 +default +fpm` to build and compile latest `PHP 7.3` version.
- After compiling latest `PHP 7.3` version, running the `phpbrew switch php-7.3.33` command to switch the this `PHP 7.3` version.
- Running the `phpbrew fpm setup --initd` command to setup the init FPM service. And the outputs are as follows:

```
$ phpbrew switch php-7.3.33
$ phpbrew fpm setup --initd
*WARNING* php-fpm --pid option requires php >= 5.6. You need to update your php-fpm.conf for the pid file location.
Writing init.d script: /etc/init.d/phpbrew-fpm
To setup the startup item, remember to run update-rc.d to link the init script:
    sudo update-rc.d phpbrew-fpm defaults
```

I don't have the issue in Debian 10 and I think the issue is going to be closed.
