### ISSUE TITLE
How replace main "php" file with phpbrew?

### ISSUE THREAD

**Issue by ttodua** [phpbrew/phpbrew#1227]
### Platformx: Ubuntu 20.04

I couldn't find in docs: So, when we have multiple versions of PHP, and want that i.e. php 7.3 was being used when system (in any app) refers to  `/usr/bin/php`  symlink, I want php 7.3 was being used (instead of the pre-installed php 7.2 which was on server before).
 which command does the job? `switch does not seem to do that.

At this moment, I have to call like this from other applications (i.e cron or whatever):
`/root/.phpbrew/php/7.3/bin/php   /myfile.php`

**Comment by tc4rv** [comment]
Hello, @ttodua 

Have you added `source /home/[user]/.phpbrew/bashrc` in your `~/(.bashrc | .zshrc)` file?
This line has to be present in your shell's .rc file (again ~/.bashrc if you're using bash or ~/.zshrc if it's zsh, for example), because it does some manipulation in your $PATH to point to the desired version.

Just for clarification, if you do `phpbrew off`, to use your system's installed PHP and look your $PATH variable, you'll see something like this (pay attention just in the first line of each example):

### PHPBREW DISABLED
```
/home/[user]/.zinit/polaris/bin: # this line!
/usr/local/sbin:
/usr/local/bin:
/usr/sbin:
/usr/bin:
/sbin:
/bin:
/usr/games:
/usr/local/games:
/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe:
/mnt/c/Windows/system32:
/mnt/c/Windows:
/mnt/c/Windows/System32/Wbem:
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:
/mnt/c/Windows/System32/OpenSSH/:
/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:
/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:
/mnt/c/Users/[user]/AppData/Local/Microsoft/WindowsApps:
/mnt/c/Users/[user]/AppData/Local/Programs/Microsoft VS Code/bin:
/mnt/c/php/php-8.0.3-nts-Win32-vs16-x64
```
Note that there is no phpbrew-related info.

### PHPBREW ENABLED (phpbrew switch php-7.4.16)
```
/home/[user]/.phpbrew/php/php-7.4.16/bin: # this line! (notice it points to the .phpbrew directory)
/home/[user]/.zinit/polaris/bin:
/usr/local/sbin:
/usr/local/bin:
/usr/sbin:
/usr/bin:
/sbin:
/bin:
/usr/games:
/usr/local/games:
/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe:
/mnt/c/Windows/system32:
/mnt/c/Windows:
/mnt/c/Windows/System32/Wbem:
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:
/mnt/c/Windows/System32/OpenSSH/:
/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:
/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:
/mnt/c/Users/[user]/AppData/Local/Microsoft/WindowsApps:
/mnt/c/Users/[user]/AppData/Local/Programs/Microsoft VS Code/bin:
/mnt/c/php/php-8.0.3-nts-Win32-vs16-x64
```

Note that, when you switch to your desired version using phpbrew (in this example the version is 7.4.16), phpbrew adds the path to the version you choose as the first option in the $PATH variable. This means that, this is the first place system will look for the `php` executable when it is called.

So, check if the phpbrew's .bashrc is being sourced in your shell's .rc file. You can echo your $PATH variable, after running `phpbrew switch [version]`, to ensure the path to the desired PHP executable is present in the start of your $PATH variable.

Hope it helps!

**Comment by ttodua** [comment]
Many thanks, i will check!
