### ISSUE TITLE
Cookbook error - not sure what's the correct fix

### ISSUE THREAD

**Issue by pbowyer** [phpbrew/phpbrew#278]
In the cookbook entry for [Install phpbrew into system-wide environment](https://github.com/phpbrew/phpbrew/wiki/Cookbook#install-phpbrew-into-system-wide-environment) it says:

```
Now export phpbrew paths to your desired paths, edit your ~/.phpbrew/init
```

There is no `~/.phpbrew/init` file. Should the edit go in `~/.bashrc`? Editing this worked for me.

Then it talks about modifying the global /etc/bashrc and adding two lines:

```
export PHPBREW_ROOT=/opt/phpbrew
source /opt/phpbrew/bashrc
```

`/opt/phpbrew/bashrc` doesn't exist - is it meant to be manually copied from `~/.phpbrew/`?

**Comment by jmfarina** [comment]
I'm having that exact same problem, I followed the cookbook guide to set it system-wide but the file /opt/phpbrew/bashrc doesn't exist. I understand that PHPBREW_ROOT can point to whichever directory, the problem is that phpbrew doesn't seem to create that bashrc file in the PHPBREW_ROOT directory.
I'm not sure that @c9s comment applies to this situation, for this would imply running phpbrew init for every user in the system. The goal is to have a global phpbrew installation (I can export the PHPBREW_ROOT globally, but I see no way of easily ensuring the initialization of phpbrew for every user).
