### ISSUE TITLE
Can't store release json file

### ISSUE THREAD

**Issue by Benjen** [phpbrew/phpbrew#454]
I have installed phpbrew on Debian Wheezy.  However when I try to install a version of PHP I get the following message:

$ sudo phpbrew install php-5.4.36 +default +mysql +gettext +mcrypt +intl +iconv +ftp +exif +dba +openssl +soap +apxs2=/usr/bin/apxs2 -- --with-libdir=lib/x86_64-linux-gnu --with-gd=shared --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr --enable-wddx --with-mysql-sock=/var/run/mysqld/mysqld.sockPHP Warning:  file_put_contents(/root/.phpbrew/php-releases.json): failed to open stream: No such file or directory in phar:///usr/bin/phpbrew/PhpBrew/ReleaseList.php on line 2
Can't store release json file

**Comment by c9s** [comment]
You can't use phpbrew with sudo, it's because PHPBrew depends on the environment variable, when you use sudo, you're missing the settings. If you want to install phpbrew to system-wide environment, please check our wiki:

https://github.com/phpbrew/phpbrew/wiki/Cookbook#install-phpbrew-into-system-wide-environment

**Comment by Benjen** [comment]
Thank you that did the trick.
