### ISSUE TITLE
ExtensionInstaller: Install multiple extensions at once

### ISSUE THREAD

**Issue by Kharag** [phpbrew/phpbrew#541]
Hi,

Would it be possible to modify the extension installer to install multiple extensions at once, e.g. 
phpbrew ext install ext1 ext2 ext3

Would make things a lot easier when maintaining multiple systems and/or installations..

**Comment by marcioAlmada** [comment]
Hi, I'm glad you solved all the reported issues.

About your suggestion. This won't be supported exactly this way because this kind of variadic command introduces too much issues:

- what if each extension has a set of arguments `phpbrew ext install A --flag_a="..." --flagb B --other-flag="..." C ... `? Soon it get's too confusing, even for the power users.
- `phpbrew ext install A B C`, how to deal with failures in case `B` install fails? Too many things can go wrong and there is a scenario the user will have to clean up the mess, as it's hard to make transactions for operations like this that **always** work.

A solution for you: according to wiki, we already support extension sets https://github.com/phpbrew/phpbrew/wiki/Setting-up-Configuration#yaml-configuration-file. I admit I haven't been maintaining this part of phpbrew actively so I don't how stable it is, but please check if the yaml configuration is enough for your use case.

Hope that helps.

**Comment by marcioAlmada** [comment]
See this topic, more specifically: https://github.com/phpbrew/phpbrew/wiki/Setting-up-Configuration#presets-of-extensions
