### ISSUE TITLE
fpm doen't run with root

### ISSUE THREAD

**Issue by x00** [phpbrew/phpbrew#581]
`sudo ~/.phpbrew/php/php-5.6.12/sbin/php-fpm` -R works

but `sudo phpbrew fpm start` asks me if I'm thinking of another command it doesn't regonise fpm

also mentioned here

https://github.com/phpbrew/phpbrew/issues/459#issuecomment-71420320

php-5.3.3
php-5.3.29
php-5.4.41
php-5.4.43
php-5.5.9
php-5.5.26
php-5.6.9
php-5.6.12

Linux Mint 17 Qiana

9000 port nginx

**Comment by Ronmi** [comment]
If you were using `phpbrew` 1.18 or older, it's not possible to pass additional arguments to `php-fpm` due to issue #618 , which is fixed in latest 1.20 version.

`phpbrew` needs several environment variables to work, which is defined in `~/.phpbrew/bashrc`, so simple `sudo phpbrew` will not work. We have an [wiki page](https://github.com/phpbrew/phpbrew/wiki/Cookbook#install-phpbrew-into-system-wide-environment) about building php system-wide.

**Comment by c9s** [comment]
The fpm subcommand shouldn't be run with sudo.
