### ISSUE TITLE
Error install any PHP Version: OSX El Capitan

### ISSUE THREAD

**Issue by wesleywillians** [phpbrew/phpbrew#592]
For any PHP version I try to instal I get this error msg:

   _readline_shell_run in readline_cli.o
  "_history_list", referenced from:
      _zif_readline_list_history in readline.o
  "_rl_mark", referenced from:
      _zif_readline_info in readline.o
  "_rl_pending_input", referenced from:
      _zif_readline_info in readline.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1

**Comment by augustohp** [comment]
You should be careful when upgrading to a major version if you want to keep compiling stuff, everything will break specially after *heart bleed* when Apple solely decided they are better patching `openssl` and `curl` by themselves.

Your trace is not useful at all, you did not give the root cause of the link error (just the end of it) but as I said, it is probably `curl` or `openssl` (or `libxml2`). Given the lack of information you will have to try everything that comes up to my mind:

1. Update **XCode tools** with `xcode-select --install`, if that doesn't work (it rarely does), download it manually.
1. Install/Upgrade *homebrew* formulas: 
    1. `brew update` to update formulas.
    1. Re-tap homebrew/php so we get their dependencies`brew tap homebrew/php --repair`.
    1. Install all formulas listed on `brew deps homebrew/php/php56 --with-gmp`.
    1. Upgrade previously installed formulas with `brew upgrade`.
1. You will probably have to force link some dependencies (you can link them elsewhere too, probably better but you need to specify the path on the variants):
    1. Link them with `brew link --force iconv`.
    1. Some I know you will have to:  `libxml2`, `curl`, `icu4c`.

I really don't know what will help you, but I have all last versions since `5.3` compiled under *El Capitan* using **phpbrew**, haven't tried `7.0` (though doing that now), so I know it works.

PS: Make sure you install a new version with `--test` :smile:

**Comment by c9s** [comment]
@augustohp++

**Comment by c9s** [comment]
Collected in wiki https://github.com/phpbrew/phpbrew/wiki/Trouble-Shooting:-Can't-build-PHP-on-OS-X-El-Capitan

Thanks @augustohp

**Comment by augustohp** [comment]
> Collected in wiki https://github.com/phpbrew/phpbrew/wiki/Trouble-Shooting:-Can't-build-PHP-on-OS-X-El-Capitan
> 
> Thanks @augustohp

I am the one in debit. I've used your tools (Onion, just to name one) and they saved my far too much time i devoted helping your projects. My main objective now is making a clone of you! We need moare!!!! Thank you very much!

**Comment by c9s** [comment]
Glad the softwares help you :) Thanks for your contributions!

**Comment by c9s** [comment]
The `_zif_readline_info` looks like related to readline or libedit library.

**Comment by augustohp** [comment]
Can't we close this issue already?

**Comment by c9s** [comment]
Yeah the new release should fix this. :)
