### ISSUE TITLE
Install Extra Apps to CurrentPhpDir and make a version to specifiable

### ISSUE THREAD

**Issue by snize** [phpbrew/phpbrew#651]
Installing phpunit with `phpbrew app get phpunit` on php5.4.45 I got message like this.

> This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.

So I needed to install phpunit 4.8.\* only for php5.4.45. I think this can be useful for other cases.

**Comment by c9s** [comment]
PRs are welcomed :)

**Comment by vokiel** [comment]
> PHPUnit 5.5 requires PHP 5.6

> PHPUnit 4.8 requires PHP 5.3.3

As I see there are two ways to fix this.

**Fixed version defined**:
The same as it is defined for Behat (if I found correct file) in https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/AppStore.php#L13-L14
The same could be done with PHPUnit: phpunit-5, phpunit-4. 

**Autodiscovery**:
Other way is to check currently used PHP version and compare it with 5.6 (minimum for PHPUnit 5.5) - if it is lower then propose link for PHPUnit 4.8.27 (latest 4.x), otherwise use the default one.

**Comment by jhdxr** [comment]
For the speciafic problem (phpunit) here, I think the first way is the quickest way to fix.

Personally, I vote for the second way since it's much more user-friendly. However, there are something more need to be discussed:
1. How to define the matches between the version of app and php.
2. We should switch the versions of relating apps, when users switch the php versions.

**Comment by vokiel** [comment]
I was thinking about the apps issue and got some ideas.

For the PHPUnit this should be easy - we know minimum requirements for every version, so it could be even hardcoded. But, if working on this, then it would be great to make it more general and usable in other cases/applications.

The installation process should be different, now the bin folder is common for every PHP version https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/Command/AppCommand/GetCommand.php#L40 It could be the symlink for the `~/.phpbrew/php/php-x.x.x/bin` (or other apps folder), and replaced on version switch.

Other idea is to add another parameter to apps install command to define targets.
Options could be:
* current version only
* all versions
* specified versions (list)

Checking for apps would then work in cascade way - first check in current version apps directory, then in main apps folder.

WDYT?

**Comment by theofidry** [comment]
@peter279k the `app` command has been removed in (#1126, #1167, #1161) to this issue can be closed.

**Comment by peter279k** [comment]
Closed via the [comment](https://github.com/phpbrew/phpbrew/issues/651#issuecomment-2184967457).
