### ISSUE TITLE
"mysql-server : Depends: mysql-server-5.5 but it is not going to be installed" getting php5 dependencies

### ISSUE THREAD

**Issue by UTANdev** [phpbrew/phpbrew#677]
Picking up from #676 :

Now that apt-get has access to the source repo, I'm getting a different error:
```
$ sudo apt-get build-dep php5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have unmet dependencies:
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Build-dependencies for php5 could not be satisfied.
```

- Running `sudo apt depends mysql-server-5.5` displays `Conflicts: mysql-server-5.5:i386` as the last line.
- The author of [this thread](http://forums.linuxmint.com/viewtopic.php?f=47&t=189162) had the same problem; he resolved it by fixing broken packages with Synaptic, but in my case, Synaptic shows no broken packages.

How can I solve this conflict in order to install the dependencies in the first step of phpbrew's requirements? Thanks.

**Comment by Ronmi** [comment]
Seems you have installed 32bit(i386) version of mysql server, which conflicts with 64bit version. Since you probably install it for some reason, it would be better to ask community of your operating system (as I remember you are using [linux mint](http://forums.linuxmint.com/)) for more information about handling package conflict.
