### ISSUE TITLE
Understanding mysql sockets

### ISSUE THREAD

**Issue by johndevsvensson** [phpbrew/phpbrew#705]
I am on Ubuntu and used standard PHP, and had no problem connecting with host = localhost. Now I've installed phpbrew, successfully built PHP 5.6 and setup cgi on Apache.

However, now I can't connect with host = localhost anymore. 

Because when I do:

```Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /var/www/testing/index.php:3 Stack trace: #0 /var/www/testing/index.php(3): PDO->__construct('mysql:dbname=te...', 'root', '') #1 {main} thrown in /var/www/testing/index.php on line 3````

Why is that?
Can I make phpbrew built PHP behave like the Ubuntu PHP version handles MySQL sockets?
Have I done something wrong?

**Comment by Ronmi** [comment]
Seems there's something wrong with your DSN according to the error message you post, could you provide the DSN string you passed to PDO?

**Comment by johndevsvensson** [comment]
Actually the only problem I could think of is when I type 127.0.0.1 instead it works.

```$db = new PDO('mysql:host=localhost;dbname=test', 'root', '');````

Gives the error above, typing 127.0.0.1 instead works. Not sure why though. Is it something with FastCGI, or phpbrew's built PHP that causes this?

**Comment by Ronmi** [comment]
Take a look into `php.ini` may solve your problem.

Passing `host=localhost` to PDO will make it connect via *unix socket* with *default path*. Since distro-provided packages may have some custom patches in it, some default values can be very different.

AFAIK, Debian (and most of its derivations) sets default mysql socket path to `/var/run/mysqld/mysql.sock`, which is different from the settings provided from php source code. So you'll have to edit your `php.ini` or pass correct DSN string to make it work.

You may want to check [pdo_mysql documentation](http://php.net/manual/en/ref.pdo-mysql.php) for more info.

I'll close this issue because phpbrew correctly provides the official settings as default. If this is not the problem, feel free to reopen it.

**Comment by c9s** [comment]
The socket path needs to be setup.

Ronmi Ren <notifications@github.com> 於 2016年4月22日 星期五寫道：

**Comment by c9s** [comment]
Note: the new phpbrew now will automatically detect your mysql socket path when mysql_config is available.
