### ISSUE TITLE
Ubuntu 16.04 Requirement

### ISSUE THREAD

**Issue by 27cm** [phpbrew/phpbrew#795]
What about Ubuntu 16.04 Requirement? Is it the same as for 13.04 and 14.04?
https://github.com/phpbrew/phpbrew/wiki/Requirement

**Comment by morozov** [comment]
From what I can see, the requirements on Ubuntu 16.04 are slightly different:

1. `php5` → `php7.0`
2. `libcurl3-openssl-dev` → `libcurl4-openssl-dev`
3. `libxslt-dev` → `libxslt1-dev`

Not sure if `libmysqlclient-dev` is required anymore, since starting PHP 5.3 [it's is recommended](http://php.net/manual/en/mysqlinfo.library.choosing.php) to use _mysqlnd_ instead.

**Comment by williamn** [comment]
@27cm I have add requirement for Ubuntu 16.04 [here](https://github.com/phpbrew/phpbrew/wiki/Requirement)
