### ISSUE TITLE
Support: Possibility to set a template php.ini / install extensions via build command

### ISSUE THREAD

**Issue by simonkulessa** [phpbrew/phpbrew#854]
Hi,

in our company we use PHPBrew amongst other things on our Jenkins servers. One of the developers asked me, if it is possible to:

1. Set a standard php.ini (template maybe) that will be used automatically by phpbrew (so that some settings will be made automatically..like memory limit)
2. When building PHPBrew automatically install some extensions like xdebug?

Thanks in advance
Simon

**Comment by c9s** [comment]
Hi @simonkulessa,

Since I have to work on many projects from clients to make a living, I don't have so much time to maintain phpbrew like the old days anymore.

In order to make the service better, I decided to offer some services for enterprises that needs support from me. If you're interested in it, please visit the link below:

https://corneltek.selz.com/item/phpbrew-enterprise-support

Thank you

**Comment by morozov** [comment]
@simonkulessa PHPBrew itself is not capable of doing this at the moment. Despite my own desire, I can't see it implemented in any near future because it's can be relatively easily scripted outside of PHPBrew:
```bash
#!/usr/bin/env bash

# this is needed to make PHPBrew properly working in a script
. ~/.phpbrew/bashrc

phpbrew install ${VERSION}
phpbrew use ${VERSION}

# install PECL or other extensions which cannot be linked statically
phpbrew ext install xdebug

# add some default configuration
phpbrew cd var
ln -s /path/to/repository/template.ini db/
```

@c9s sorry if I stole your client :-)
