### ISSUE TITLE
PHP's exec() and shell_exec() not using phpbrew php installation but the default one

### ISSUE THREAD

**Issue by radixs** [phpbrew/phpbrew#954]
Hi,
I have a problem which is when I try to launch a php script inside another php script via shell_exec() or exec() it is using the default system PHP installation instead of the one provided by phpbrew.

When php is being launched via apache/browser or I try to launch the scripts in the terminal using the cli mode everything works fine and it uses my phpbrew php version.

I can point towards a specific php installation when invoking the exec() but that is a dirty solution. Has anyone any idea why exec() is not using the php installation that phpbrew is switched onto?

### Platform

OS:

   Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-104-generic x86_64)

Phpbrew version: 1.23.0

**Comment by morozov** [comment]
@radixs are you running your first script from CLI? In this case, instead of using just `php` as the shell command, use the value of the [`PHP_BINARY`](http://php.net/manual/en/reserved.constants.php#constant.php-binary) constant. It will contain the absolute path to the `php` currently being used. It will make the scripts better portable regardless of whether they are run in the PHPBrew environment or not.

Otherwise, if the first script is run from `mod_php` or `php-fpm`, you may consider loading `~/.phpbrew/bashrc` in the shell before running PHP (see https://github.com/phpbrew/phpbrew/issues/559#issuecomment-129430036).

**Comment by radixs** [comment]
I will try the PHP_BINARY, seems very useful. But the first script is being run via apache/browser which is using the correct phpbrew binary too (as it happens with running the script via terminal/cli). Will update this comment if it works when I will catch a free moment!

Thanks for the tip so far!
